name: First CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          sudo apt update -y
          sudo apt install -y g++ cmake make python3 python3-pip 
          
      - name: Compile Prime.cpp
        run: |
          mkdir -p build
          g++ -o build/Prime.exe Prime.cpp

      - name: Run Python tests
        run: |
          python3 Unit_Test.py
          
  windows-build-and-test:
    needs: ubuntu-build-and-test
    runs-on: windows-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup environment
      run: |
        choco install mingw
        choco install python3
        choco install python3-pip 

    - name: Compile Prime.cpp
      run: |
        mkdir -p build
        g++ -o build/Prime.exe Prime.cpp

    - name: Run Python tests
      run: |
        python Unit_Test.py
