name: First CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          sudo apt update -y
          sudo apt install g++ cmake make python3 python3-pip 
          python3 pip install --upgrade pip pytest

      - name: Compile Prime.cpp
        run: |
          g++ -o Prime.exe Prime.cpp

      - name: Run Python tests
        run: |
          python3 Unit_Test.py
