name: First CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y g++ cmake make python3 python3-pip pip3 install pytest

      - name: Create and build directory
        run: |
          mkdir -p build
          g++ -o g++ -o Prime.exe ./src/Prime.cpp

      - name: Run Python tests
        run: |
          pytest ./tests --exe ./Prime.exe
