name: First CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          sudo apt update -y
          sudo apt install -y g++ cmake make python3 python3-pip 
          python3 -m pip install --upgrade pip 
          python3 -m pip install unittest-xml-reporting

      - name: Compile Prime.cpp
        run: |
          mkdir -p build
          g++ -o build/Prime.exe Prime.cpp

      - name: Set execution permissions
        run: chmod +x build/Prime.exe

      - name: Run Python tests
        run: |
          python3 Unit_Test.py
